### ISSUE TITLE
Exception when delete query

### ISSUE THREAD

**Issue by bennybak** [groveco/django-sql-explorer#306] opened 2017-11-15 18:54 UTC
Where I try to delete the query (/explorer/2/delete) I received the following error:

Request Method:	GET
Request URL:	http://127.0.0.1/app/explorer/2/delete
Django Version:	1.10.6
Exception Type:	TypeError
Exception Value:	
change_permission() got an unexpected keyword argument 'pk'
Exception Location:	/home/xapp/.virtualenvs/car2/local/lib/python2.7/site-packages/explorer/views.py in has_permission, line 77
Python Executable:	/home/xapp/.virtualenvs/car2/bin/python2
Python Version:	2.7.12

django-sql-explorer==1.1.1

**Comment by chrisclark** [comment] 2018-01-12 23:04
Any chance you can write a unit test to dupe the issue? I can give it a go as well, perhaps in a day or two. Thanks!

**Comment by Cadmus** [comment] 2018-01-31 12:20
did you resolve this isssue , now its showing error

change_permission() got an unexpected keyword argument 'pk'

**Comment by HenryMehta** [comment] 2018-02-10 15:31
I've got the same issue - has anyone made progress resolving it?

**Comment by HenryMehta** [comment] 2018-02-10 16:50
The issue is in permissions.py.

    def change_permission(request):
        return app_settings.EXPLORER_PERMISSION_CHANGE(request.user)

should be 

    def change_permission(request, *args, **kwargs):
        return app_settings.EXPLORER_PERMISSION_CHANGE(request.user)

I notice in the Master branch this is the case, but is not the branch being downloaded by `pip install`.   I downloaded the Master branch and got a different error, namely: `django.core.exceptions.ImproperlyConfigured: EXPLORER_CONNECTIONS contains (Default, readonly), but readonly is not a valid Django DB connection.`

I am not sure which version is being downloaded, but I would like to fork whichever it is and fix this issue.

**Comment by HenryMehta** [comment] 2018-02-10 17:04
And the solution to `django.core.exceptions.ImproperlyConfigured: EXPLORER_CONNECTIONS contains (Default, readonly), but readonly is not a valid Django DB connection.`

is to set them to the new standard:

    EXPLORER_CONNECTIONS = { 'Default': 'default' } 
    EXPLORER_DEFAULT_CONNECTION = 'default'

**Comment by Cadmus** [comment] 2018-02-10 21:59
I have made a pull request for this issue, please check it.

**Comment by chrisclark** [comment] 2018-04-01 23:56
Merged and resolved. Thanks!

**Closed by chrisclark** 2018-04-01 23:56 UTC
Labels: bug
